name: PR
on:
  pull_request:
    branches:
      - master
jobs:
  Windows:
    name: Windows
    runs-on: windows-2016
    timeout-minutes: 45
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - run: yarn install --frozen-lockfile

      - run: yarn build

      - name: Setup MSBuild.exe
        uses: warrenbuckley/Setup-MSBuild@v1

      - name: Setup Nuget.exe
        uses: warrenbuckley/Setup-Nuget@v1

      - name: Install react-native cli
        run: npm install -g react-native-cli

      - name: Init new project
        run: cd ${{ runner.temp }} && react-native init testcli --version 0.59.10

      - name: Install rnpm-plugin-windows
        run: cd ${{ runner.temp }}\testcli && yarn add rnpm-plugin-windows

      - name: Apply windows template
        run: cd ${{ runner.temp }}\testcli && react-native windows

      - name: install react-native-device-info from local repo
        run: cd ${{ runner.temp }}\testcli && yarn add react-native-device-info@file:${{ runner.workspace }}\react-native-device-info

      - name: react-native link react-native-device-info
        run: cd ${{ runner.temp }}\testcli && react-native link react-native-device-info

      - name: Nuget restore
        run: nuget restore ${{ runner.temp }}\testcli\windows\testcli.sln

      - name: Build Windows Solution
        run: msbuild ${{ runner.temp }}\testcli\windows\testcli.sln /nologo /nr:false /p:PreferredToolArchitecture=x64 /p:platform="x86" /p:configuration="Debug"

      # Not sure why the ReactNativeWebViewBridge project doesn't build, but its not needed for this verification, and unrelated to react-native-device-info
      - name: Dont build ReactNativeWebViewBridge project
        run: |
          Select-String -pattern "{7596216B-669C-41F8-86DA-F3637F6545C0}.Debug|x86.Build.0" -NotMatch -SimpleMatch -LiteralPath ${{ runner.temp }}\testcli\windows\testcli.sln | Select-Object -ExpandProperty Line | Out-File ${{ runner.temp }}\testcli\windows\testcli.sln2
          copy ${{ runner.temp }}\testcli\windows\testcli.sln2 ${{ runner.temp }}\testcli\windows\testcli.sln
          (Get-Content ${{ runner.temp }}\testcli\node_modules\react-native-windows\ReactWindows\ReactNative\ReactNative.csproj -Raw) -replace "(?s)<ProjectReference Include=`"...ReactNativeWebViewBridge.ReactNativeWebViewBridge.csproj.*ProjectReference>","" | Out-File ${{ runner.temp }}\testcli\node_modules\react-native-windows\ReactWindows\ReactNative\ReactNative.csproj2
          copy ${{ runner.temp }}\testcli\node_modules\react-native-windows\ReactWindows\ReactNative\ReactNative.csproj2 ${{ runner.temp }}\testcli\node_modules\react-native-windows\ReactWindows\ReactNative\ReactNative.csproj
        shell: powershell

      - name: Build Windows Solution
        run: msbuild ${{ runner.temp }}\testcli\windows\testcli\testcli.csproj /nologo /nr:false /p:PreferredToolArchitecture=x64 /p:platform="x86" /p:configuration="Debug"